version: "3"

services:
  ##################################
  # Setup node container
  ##################################
  server:
    container_name: server-ereport
    build: ./server
    expose:
      - 8017
    ports:
      - 8017:8017
    volumes:
      - "./server:/app/server"
  ##################################
  # Setup client container
  ##################################
  client:
    container_name: client-ereport
    build: ./client
    stdin_open: true
    tty: true
    expose:
      - 3000
      - 35729
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - "./client:/app/client"
      - "/app/client/node_modules"
      - "/app/client/build"
    environment:
      - CHOKIDAR_USEPOLLING=true
